version: '3'

services:
  web:
    image: albericwalsh/ecommerce:WEB-ecommerce
    container_name: server_ecomerce_web
    ports:
      # local:container
      - "80:80"
    build: ./WEB
    depends_on:
      - db

  db:
    build: ./BDD
    image: albericwalsh/ecommerce:BDD-ecomerce
    container_name: server_ecomerce_bdd
    ports:
      - "3306:3306"
    volumes:
      # Volume de la base de données
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database.sqlite
      MYSQL_ROOT_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"