version: '3'

services:
  web:
    image: albericwalsh/ecommerce:WEB-ecommerce
    build: ./WEB/
    container_name: server_ecomerce_web
    ports:
      - "8080:8080"
    networks:
      network:
        ipv4_address: 10.92.100.10
    depends_on:
      - db

  db:
    image: albericwalsh/ecommerce:BDD-ecomerce
    build: ./BDD/
    container_name: BDD
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
    networks:
      network:
            ipv4_address: 10.92.100.11

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.92.100.0/24
