version: '3'

services:
  web:
    build: ./WEB/
    image: albericwalsh/ecommerce:WEB-ecommerce
    container_name: server_ecomerce_web
    ports:
      # local:container
      - "80:80"
    depends_on:
      - db

  db:
    build: ./BDD/
    image: albericwalsh/ecommerce:BDD-ecomerce
    container_name: server_ecomerce_bdd
    command: 
    ports:
      - "3306:3306"
    volumes:
      # Volume de la base de données
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "database"
    # docker-entrypoint-initdb:
    #   command: ["mysqld", "--initialize-insecure"]